<?php
 $title = 'Student List';
 $this->headTitle($title);
 ?>
<!-- Main Content --> 
<div id="page-wrapper">
  <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Student <small>Statistics Overview</small>
          
                  <button type="button" id="addStudent" class="btn btn-primary" style="float: right;">
                <?php echo $this->translate('Add New ');?>+</button>
            </h1>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>User Id</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($this->listStudent as $key => $val) {?>
                <tr>
                    <td><?php echo $val['user_id']; ?></td>
                    <td><?php echo $val['s_name']; ?></td>
                    <td><?php echo $val['email']; ?></td>
                    <td>Edit</td>
                </tr>
                <?php } ?>
              </tbody>
        </table>
    </div>
  </div>
</div>


