<div id="page-wrapper">
  <div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Dashboard <small>Statistics Overview</small>
            </h1>
        </div>
    </div>
    <!-- /.row -->
    <?php $listTopics = $this->listTopics;?>
        <div class="row">
            <?php foreach ($listTopics as $val) { ?>
            <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $val['t_name'] ?></h3>
                        </div>
                        <div class="panel-body">
                            <p>Hello Description of <?php echo $val['description'] ?></p>
                        </div>
                    </div>
                </div>
             <?php }?>
        </div>
    </div>
<!-- /.container-fluid -->
</div>